spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/
logging:
  level:
    org.springframework.web.socket.server.HandshakeInterceptor: DEBUG
    org.springframework.web.socket.WebSocketHandler: DEBUG
    org.springframework.web.socket.sockjs: DEBUG   # if you ever add SockJS

